import Head from 'next/head'
import { CarouselFirst } from './carousel'
import "react-responsive-carousel/lib/styles/carousel.min.css";
import styles from '../styles/Home.module.css'
import Introduction from './introduction'
import TheBride from './theBride'
import TheWedding from './theWedding'
import HealthProtocool from './healthProtocool';
import TheWish from './theWish';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:100,300,500,600,700,800&display=optional"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Moon+Dance:100,300,500,600,700,800&display=optional"
          rel="stylesheet"
        />
        <link 
          href="https://fonts.googleapis.com/css?family=Open+Sans:100,300,500,600,700,800&display=swap"
          rel="stylesheet" 
        ></link>
      </Head>

      <main className={styles.main}>
        <Introduction />
        <TheBride />
        <div style={{width: '100%', height: '10px', backgroundColor: '#F1931E', marginTop: '15px', marginBottom: '15px'}}/>
        <CarouselFirst />
        <div style={{width: '100%', height: '10px', backgroundColor: '#F1931E', marginTop: '15px', marginBottom: '15px'}}/>
        <TheWedding />
        <div style={{width: '100%', height: '10px', backgroundColor: '#F1931E', marginTop: '15px', marginBottom: '15px'}}/>
        <CarouselFirst />
        <div style={{width: '100%', height: '10px', backgroundColor: '#F1931E', marginTop: '15px', marginBottom: '15px'}}/>
        <HealthProtocool />
        <div style={{width: '100%', height: '10px', backgroundColor: '#F1931E', marginTop: '15px', marginBottom: '15px'}}/>
        <CarouselFirst />
        <div style={{width: '100%', height: '10px', backgroundColor: '#F1931E', marginTop: '15px', marginBottom: '15px'}}/>
        <TheWish />
        <div style={{width: '100%', height: '10px', backgroundColor: '#F1931E', marginTop: '15px', marginBottom: '15px'}}/>
        <CarouselFirst />
        <div style={{width: '100%', height: '10px', backgroundColor: '#F1931E', marginTop: '15px', marginBottom: '15px'}}/>
      </main>
    </div>
  )
}
